export const UI_CONSTANTS = {
  AXIS_SIZE: 300,
  TOKEN_SIZE: 35,
  AXIS_PADDING_RATIO: 0.06,
  FONT_SIZE_RATIO: 0.05,
  MIN_FONT_SIZE: 10,
  AVAILABLE_SPACE_RATIO: 0.8,
  CHAR_WIDTH_RATIO: 0.6,
  INITIAL_POSITION: {
    CENTER_X: 0.5,
    CENTER_Y: 0.5,
    RADIUS: 0.2,
    CIRCLE_CENTER_X: 0.3,
    CIRCLE_CENTER_Y: 0.4
  },
  POSITION_BOUNDS: {
    MIN: 0.06,
    MAX: 0.94
  }
}
